### PR TITLE
Update Application.java

### PR DESCRIPTION
**Pull request by AkiraTenchi**
Some minor changes in the if statements.

### CODE REVIEW

**Comment by goxr3plus** [comment]
Tell me how happy you will be if i merge :)?

**Comment by AkiraTenchi** [comment]
Really happy, smash doesn't work therwise ;)

**Comment by goxr3plus** [comment]
Ready :)

**Comment by goxr3plus** [comment]
If you are really interested on it i can make you a collaborator ao you can directly commit on master branch.

**Pull request merged**
